sudo: required
language: bash
services:
- docker
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq default-jdk
- docker run inaetics/cagent_builder build_script > cagent_builder.sh && chmod +x cagent_builder.sh
install:
- ./cagent_builder.sh make_bundles
deploy:
  provider: bintray
  file: ${TRAVIS_BUILD_DIR}/deployment.json
  user: bpetri
  key:
    secure: e6zBLdV6QpRluiq8DepaWs/sJ9K+9pfCBy4kKw4DDEXaFbigUWZkiWaSwpEeJu5sck+WtnqByegN2Igg+1Yv/KggLiQ66niU7zVzM0JgGNOU8Z9/DLeZKodr13tEkhd0oyNLr7H6ZkUcT9CGaDBqlO+5JGzXHjlYSngL8u03ICd7EMTUwbWYSIlBoXro0CTmkoHNgGxGwSZVq3buozkfPx7l6L1EGGe4HwC6/VLr7JAxHPU2tE7QFFM89zExF1ryoewWEYJDiQgYNPzXf1JIydzrtTzeDxkV9mUZKB6F417D91MNtmEAvy83OR6o/cpzbjc+Fqk917RIp2u9S0fmUqjoc3XuOZBnSlFnHHD6A+JF0qZxoDDe3rDRPB7NccgWI4mnhBNODQStdv4WKACGEJMGNngbEJbaPXgNaeqFWsaBfAhtt15zF9iM8e4j388jU6KiEeQkCUYNIPQxXTqOjapN+TSzWaUqjSk65jGV7Byd6Bfz8SkhClntGBJ1IYl13OQ/g3DDUfVguE70Mi7hxjcwNke4UxVOZSsh0pSMc9YiBg6KOQX36xinSecnborl6NGrYyKt5ULyUIStkYwvzvOoI+I1fG6FqCCC2/9VfoHf5MkbCF1z+IW3OFxEHRwoDvBwnTbNhkdvE2EjwCBaw6Zdqx89fWE1EB6KAQPvk8M=
