sudo: required

language: bash

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq default-jdk
  - docker run inaetics/cagent_builder build_script > cagent_builder.sh && chmod +x cagent_builder.sh

install:
  - ./cagent_builder.sh make_bundles

deploy:
  provider: bintray
  file: $TRAVIS_BUILD_DIR/deployment.json
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
